language: node_js
node_js:
  - "node"
install:
  - npm install -g codecov istanbul
script:
  - npm install
  - npm test
after_success:
  - istanbul cover test/test-index.js --reporter lcovonly -- -R spec
  - codecov